name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: OO Test
      id: oo-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: OO Test
        setup-command: ''
        command: gradle test
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        OO-TEST_RESULTS: "${{steps.oo-test.outputs.result}}"
      with:
        runners: oo-test
